// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIow0q6RXexCFpxNWwz8wKyp8Q99iEkys',
    appId: '1:736802989796:web:c8e2776c4525ff28f7eef1',
    messagingSenderId: '736802989796',
    projectId: 'wild-steps',
    authDomain: 'wild-steps.firebaseapp.com',
    storageBucket: 'wild-steps.appspot.com', // <-- FIXED
    measurementId: 'G-8TD9X667WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpHs9ogxsirM8kan04k20XRQ8SRJeZUOE',
    appId: '1:736802989796:android:361725d317b016f1f7eef1',
    messagingSenderId: '736802989796',
    projectId: 'wild-steps',
    storageBucket: 'wild-steps.appspot.com', // <-- FIXED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwp6dsTFAsdW7rjeZ618gRgAOOAxYK5hc',
    appId: '1:736802989796:ios:5131dcf332298132f7eef1',
    messagingSenderId: '736802989796',
    projectId: 'wild-steps',
    storageBucket: 'wild-steps.appspot.com', // <-- FIXED
    iosBundleId: 'com.example.wildStep',
  );
}
